//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public int Event_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime AnnouncementDate { get; set; }
        public string IssuedBY { get; set; }
        public string FileDirectory { get; set; }
        public string ImageDirectory { get; set; }
        public int Admin_ID { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
    }
}
