//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class GUARDIAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUARDIAN()
        {
            this.GUARDIANREVIEWs = new HashSet<GUARDIANREVIEW>();
        }
    
        public int Guardian_ID { get; set; }
        public string GuardianName { get; set; }
        public string GuardianEmail { get; set; }
        [DataType(DataType.Password)]
        public string GuardianPassword { get; set; }
        public string GuardianContactNumber { get; set; }
        public string GuardianAddress { get; set; }
        public int Admin_ID { get; set; }
        public int Student_ID { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUARDIANREVIEW> GUARDIANREVIEWs { get; set; }
    }
}
