//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int Payment_ID { get; set; }
        public int PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMonth { get; set; }
        public int Student_ID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
